# ============================================================================
# SDC Constraints — ADC Controller
# 统一版（DC + PrimeTime 兼容）— 2026-07-22 由 /sdc-manager 回灌统一
# ----------------------------------------------------------------------------
# 历史修订（统一回灌）：
#   ① 删除 set_clock_relationship（DC O-2018.06 为 unknown command CMD-005，
#      该命令为 Synopsys 较新版本才有）。adc_clkn 改用 create_generated_clock
#      -invert，语义等价且 DC/PT 均支持，STA 做 half-cycle 路径分析。
#   ② clock_groups -group 由裸名 { pclk } 改为 [get_clocks pclk]（DC 要求
#      -group 接 clock collection，裸名报 CMD-012 "extra positional option"）。
#   ③ false_path 异步输入从 "-to clk [get_ports x]" 调整为
#      "-from [get_ports x] -to [get_clocks clk]"（顺序无关，但显式 -from/-to
#      更稳，DC/PT 通用）。
# ----------------------------------------------------------------------------
# Clock structure:
#   PCLK      — APB clock, up to 200 MHz (external)
#   ADC_CLK   — ADC working clock, up to 60 MHz (from CKCU)
#   ADC_CLKn  — ADC inverted clock, same frequency as ADC_CLK, 180° phase shift
#               (generated by CKCU from same source as ADC_CLK, NOT internally
#               generated by RTL). 同源反相 = 同步时钟，半周期路径，不设
#               false_path / 不进 asynchronous group（见 [[sync-clock-not-cdc]]）。
# ============================================================================

# --- Clock definitions ---

create_clock -name pclk      -period 5.000 [get_ports pclk]                ;# 200 MHz

# ADC domain: adc_clk + adc_clkn 两个独立顶层输入端口，均来自 CKCU 同源 PLL，
# 同频 60MHz、固定 180° 相位差。注意：两者是独立输入端口，芯片内部无 adc_clk
# →adc_clkn 物理路径，故不能用 create_generated_clock（PT 报 PTE-075 "no path
# to master"）。正确表达：两个独立 create_clock，用 -waveform 给 adc_clkn 半周
# 期相位偏移（rise@8.333 = 180°），STA 据此对 adc_clk↔adc_clkn 做半周期路径
# 分析，且不进 asynchronous group（二者同步）。见 [[sync-clock-not-cdc]]。
create_clock -name adc_clk   -period 16.667 [get_ports adc_clk]            ;# 60 MHz
create_clock -name adc_clkn  -period 16.667 -waveform {8.333 16.667} [get_ports adc_clkn]

# pCLK ↔ ADC 域：异步（不同源），分两个 group
# 注：-group 必须接 [get_clocks ...] collection，裸时钟名 DC 报 CMD-012
set_clock_groups -asynchronous \
    -group [get_clocks pclk] \
    -group [get_clocks {adc_clk adc_clkn}]

# --- Input / Output delays ---

# APB interface (PCLK domain @ 200MHz, T=5.0ns)
# IO delay 占周期 30%（input 1.5 + output 1.5 = 3.0），内部预算 2.0ns。
# 业界 APB slave 惯例：external 段占周期 50-80%，input/output 对称切分，
# 平衡档各 30% 为常见默认。详见 [[apb-io-delay-budget]]。
# 演进：初版 2.5ns 各 50%（合 100% T → 内部零余量，PCLK WNS −0.19ns/32 违例）
#   → 2.0ns 激进档（内部 1.0ns）收敛 → 1.5ns 平衡档（内部 2.0ns，更稳妥通用）。
#   内部组合逻辑实测仅 0.19ns，2.0ns 内部预算余量充足（含 ssg 慢角 / OCV 裕度）。
#   注：此为合理 placeholder，SoC 集成阶段须按真实 APB 互连延迟重定
#   （真值由 SoC top-level timing budget 定，转 /sdc-manager 同步模式）。
set_input_delay  -clock pclk    1.5 [get_ports "paddr* pwrite psel penable pwdata*"]
set_output_delay -clock pclk    1.5 [get_ports "prdata* pready pslverr"]

# Analog interface (ADC_CLK domain — async outputs to analog IP)
# SOC, MUXON, ch_sel are generated at adc_clkn posedge;
# analog detects them at next adc_clk posedge (~8.3ns).
# preempt_rst_n is a combinational pulse driven in ST_LP_PREEMPT (adc_clk
# domain), asserted one cycle before HP SOC — same domain as SOC/MUXON.
# Set conservative IO delay to allow synthesis margin.
set_output_delay -clock adc_clk  4.0 [get_ports "soc muxon ch_sel* preempt_rst_n"]
set_input_delay  -clock adc_clk  4.0 [get_ports "eoc adc_data*"]

# Calibration
set_output_delay -clock adc_clk  4.0 [get_ports cal_st]
set_input_delay  -clock adc_clk  4.0 [get_ports "cal_done cal_val*"]

# External triggers (async to ADC_CLK)
set_input_delay  -clock adc_clk  4.0 [get_ports "mctm_trig*"]

# Interrupt / DMA (async outputs)
# PCLK 域 IO delay 与 APB 一致 1.5ns（平衡档 30%，同 [[apb-io-delay-budget]]）
set_output_delay -clock pclk     1.5 [get_ports "adc_int dma_ndreq"]
set_input_delay  -clock pclk     1.5 [get_ports dma_ack]

# --- False paths (async crossings) ---

# PCLK ↔ ADC_CLK: async domain crossing. Only adc_en is synchronized (2-stage
# in adc_regfile). All other PCLK-domain config registers (spt0/spt1/
# smpl_interval/cont_mode/data_align/int_en/dma_ctrl/lp_seq/hp_seq/seq_len/
# trig config bits) are read directly in the ADC_CLK domain — they are stable
# between EOC events after adc_en sync completes. eoc_idx (seq_ptr at EOC,
# ADC_CLK domain) is read in PCLK at the synced LP/HP EOC edge — stable by
# then (set ~2 adc_clk + 2 pclk earlier). All covered by this false_path.
set_false_path -from [get_clocks pclk]    -to [get_clocks adc_clk]
set_false_path -from [get_clocks adc_clk] -to [get_clocks pclk]

# adc_clkn ↔ adc_clk: same source, 180° phase shift — SYNCHRONOUS clocks.
# These are NOT asynchronous: STA treats adc_clkn→adc_clk as half-cycle
# paths (generated clock with invert). Do NOT set false_path here — that
# would mask real timing paths. RTL samples adc_clkn-domain signals with a
# single flop in adc_clk (1-stage, no 2-stage synchronizer needed), see
# adc_seq_fsm.v muxon_clk. [[sync-clock-not-cdc]]
# (PCLK ↔ ADC_CLK remains async — false_path above.)

# MCTM triggers (async input, goes through sync_cell)
set_false_path -from [get_ports "mctm_trig*"] -to [get_clocks adc_clk]

# DMA ack (can be async)
set_false_path -from [get_ports dma_ack] -to [get_clocks adc_clk]

# --- Multicycle paths (if any) ---
# (none currently — all paths within ADC_CLK domain complete in 1 cycle @ 60MHz)

# --- Operating conditions / driving / loading ---
# operating_conditions 由综合脚本按角设定（tt/ssg/ffg 各角在 source 本 SDC
# 后 set_operating_conditions），不在此硬编码——多角综合时各角库不同，
# 硬编码单角会让其他角 source 报 UID-131/UID-1220。
# driving_cell/load 为约束相关，跨角通用（cell 名 INVD1BWP12T40P140 各角均存在）：
set_driving_cell -lib_cell INVD1BWP12T40P140 [all_inputs]
set_load 0.05 [all_outputs]

# --- Reports ---
# 注：report_area/report_power 是 DC 命令，PrimeTime 无此命令。
# 用 sdc_report 变量控制：DC 综合 source 时执行，PT STA 跳过。
# DC 脚本 source 前 set sdc_report 1；PT 脚本 source 前 set sdc_report 0。
if {[info exists sdc_report] == 0} { set sdc_report 1 }
if {$sdc_report} {
    report_timing -nworst 10 > reports/timing.rpt
    report_area         > reports/area.rpt
    report_power        > reports/power.rpt
}
