// Auto-generated by regmap-gen — DO NOT EDIT
// Module: adc_controller

//==============================================================================
// Address Macros (APB 32-bit, 4-byte aligned)
//==============================================================================
`define ADC_CTRL         32'h00
`define ADC_STAT         32'h04
`define ADC_TRIG         32'h08
`define ADC_INT_EN       32'h0C
`define ADC_INT_STAT     32'h10
`define ADC_CAL_CTRL     32'h14
`define ADC_CAL_VAL      32'h18
`define ADC_ANA_CFG      32'h1C
`define ADC_ANA_REG      32'h20
`define ADC_LP_DATA0     32'h24
`define ADC_LP_DATA1     32'h28
`define ADC_LP_DATA2     32'h2C
`define ADC_LP_DATA3     32'h30
`define ADC_LP_DATA4     32'h34
`define ADC_LP_DATA5     32'h38
`define ADC_LP_DATA6     32'h3C
`define ADC_LP_DATA7     32'h40
`define ADC_LP_DATA8     32'h44
`define ADC_LP_DATA9     32'h48
`define ADC_LP_DATA10    32'h4C
`define ADC_LP_DATA11    32'h50
`define ADC_LP_DATA12    32'h54
`define ADC_LP_DATA13    32'h58
`define ADC_LP_DATA14    32'h5C
`define ADC_LP_DATA15    32'h60
`define ADC_LP_DATA16    32'h64
`define ADC_LP_DATA17    32'h68
`define ADC_LP_DATA18    32'h6C
`define ADC_LP_DATA19    32'h70
`define ADC_LP_DATA20    32'h74
`define ADC_LP_DATA21    32'h78
`define ADC_LP_DATA22    32'h7C
`define ADC_LP_DATA23    32'h80
`define ADC_LP_DATA24    32'h84
`define ADC_LP_DATA25    32'h88
`define ADC_HP_DATA0     32'hA4
`define ADC_HP_DATA1     32'hA8
`define ADC_HP_DATA2     32'hAC
`define ADC_HP_DATA3     32'hB0
`define ADC_DMA_CTRL     32'hB4
`define ADC_LP_SEQ0      32'hB8
`define ADC_LP_SEQ1      32'hBC
`define ADC_LP_SEQ2      32'hC0
`define ADC_LP_SEQ3      32'hC4
`define ADC_LP_SEQ4      32'hC8
`define ADC_LP_SEQ5      32'hCC
`define ADC_LP_SEQ6      32'hD0
`define ADC_LP_SEQ7      32'hD4
`define ADC_HP_SEQ       32'hD8
`define ADC_LP_SEQ_LEN   32'hDC
`define ADC_HP_SEQ_LEN   32'hE0

// LP_DATA base and stride macro
`define ADC_LP_DATA_BASE   32'h24
`define ADC_LP_DATA_STRIDE 4

// HP_DATA base and stride macro
`define ADC_HP_DATA_BASE   32'hA4
`define ADC_HP_DATA_STRIDE 4

// LP_SEQ base and stride
`define ADC_LP_SEQ_BASE  32'hB8
`define ADC_LP_SEQ_STRIDE 4

//==============================================================================
// CTRL — Control Register (0x00), 16-bit RW
//==============================================================================
`define ADC_CTRL_ADC_EN          0
`define ADC_CTRL_SW_RST          1
`define ADC_CTRL_DATA_ALIGN_L    2
`define ADC_CTRL_DATA_ALIGN_H    3
`define ADC_CTRL_DATA_ALIGN_W    2
`define ADC_CTRL_SMPL_INTERVAL_L 4
`define ADC_CTRL_SMPL_INTERVAL_H 7
`define ADC_CTRL_SMPL_INTERVAL_W 4
`define ADC_CTRL_SPT0_L          8
`define ADC_CTRL_SPT0_H          10
`define ADC_CTRL_SPT0_W          3
`define ADC_CTRL_SPT1_L          11
`define ADC_CTRL_SPT1_H          13
`define ADC_CTRL_SPT1_W          3

//==============================================================================
// STAT — Status Register (0x04), 16-bit RO
//==============================================================================
`define ADC_STAT_ADC_BUSY        0
`define ADC_STAT_LP_BUSY         1
`define ADC_STAT_HP_BUSY         2
`define ADC_STAT_CAL_BUSY        3

//==============================================================================
// TRIG — Trigger Control Register (0x08), 16-bit RW
//==============================================================================
`define ADC_TRIG_LP_SW_TRIG       0
`define ADC_TRIG_LP_SW_TRG_EN    1
`define ADC_TRIG_LP_MCTM_EN      2
`define ADC_TRIG_LP_TRG_SEL_L    3
`define ADC_TRIG_LP_TRG_SEL_H    6
`define ADC_TRIG_LP_TRG_SEL_W    4
`define ADC_TRIG_HP_SW_TRIG      8
`define ADC_TRIG_HP_SW_TRG_EN    9
`define ADC_TRIG_HP_MCTM_EN      10
`define ADC_TRIG_HP_TRG_SEL_L    11
`define ADC_TRIG_HP_TRG_SEL_H    14
`define ADC_TRIG_HP_TRG_SEL_W    4

//==============================================================================
// INT_EN — Interrupt Enable (0x0C), 16-bit RW
// INT_STAT — Interrupt Status (0x10), 16-bit RW1C
//==============================================================================
`define ADC_INT_LP_EOC           0
`define ADC_INT_LP_SEQ_DONE      1
`define ADC_INT_HP_EOC           2
`define ADC_INT_HP_SEQ_DONE      3
`define ADC_INT_HP_PREEMPT       4
`define ADC_INT_OVERRUN          5

//==============================================================================
// CAL_CTRL — Calibration Control (0x14), 16-bit RW
//==============================================================================
`define ADC_CAL_CTRL_CAL_ST      0
`define ADC_CAL_CTRL_CAL_DONE    1

//==============================================================================
// CAL_VAL — Calibration Value (0x18), 16-bit RO
//==============================================================================
`define ADC_CAL_VAL_L            0
`define ADC_CAL_VAL_H            5
`define ADC_CAL_VAL_W            6

//==============================================================================
// LP_DATAn / HP_DATAn — Sequence Data Registers (32-bit RO)
//==============================================================================
`define ADC_SEQ_DATA_VALID       31
`define ADC_SEQ_DATA_L           0
`define ADC_SEQ_DATA_H           15
`define ADC_SEQ_DATA_W           16

//==============================================================================
// DMA_CTRL — DMA Control (0xB4), 16-bit RW
//==============================================================================
`define ADC_DMA_CTRL_EN          0
`define ADC_DMA_CTRL_LP_EOC      1
`define ADC_DMA_CTRL_LP_SEQ      2
`define ADC_DMA_CTRL_HP_EOC      3
`define ADC_DMA_CTRL_HP_SEQ      4
`define ADC_DMA_CTRL_OVERRUN     5

//==============================================================================
// LP_SEQ / HP_SEQ — Sequence Entry Field (per entry, 8-bit APB 占位)
//   entry 内只低 W_CH_SEL bit = ch_sel 有效，[7:W_CH_SEL] rsv 读回 0（写无效）。
//   位宽随 ADC_NUM_CH 参数化：$clog2(ADC_NUM_CH)（8→3, 16→4, 26→5, 32→5）。
//   此处宏按 32 通道上限（W_CH_SEL=5）定义；adc_uvm_pkg 按实际 ADC_NUM_CH
//   重定义 ADC_SEQ_CH_SEL_W / ADC_SEQ_ENTRY_MASK / ADC_SEQ_REG_MASK 供 sweep 用。
//==============================================================================
`define ADC_SEQ_ENTRY_CH_SEL_L   0
`define ADC_SEQ_ENTRY_CH_SEL_H   4
`define ADC_SEQ_ENTRY_CH_SEL_W   5

//==============================================================================
// LP_SEQ_LEN — LP Sequence Length (0xDC), W_LP_SEQ_LEN-bit RW, reset ADC_NUM_CH
//   位宽随 ADC_NUM_CH 参数化：$clog2(ADC_NUM_CH+1)（8→4, 26→5, 32→6）。
//   此处宏按 32 通道上限（6bit）定义；adc_uvm_pkg 按实际 ADC_NUM_CH 重定义
//   ADC_LP_SEQ_LEN_W 供 sequence sweep mask 用。
// HP_SEQ_LEN — HP Sequence Length (0xE0), 3-bit RW, reset 4 (固定)
//==============================================================================
`define ADC_LP_SEQ_LEN_L         0
`define ADC_LP_SEQ_LEN_H         5
`define ADC_LP_SEQ_LEN_W         6
`define ADC_HP_SEQ_LEN_L         0
`define ADC_HP_SEQ_LEN_H         2
`define ADC_HP_SEQ_LEN_W         3
